from django.db import models

# class Zipcode(models.Model):
#     code = models.IntegerField()
#     state_abv = models.CharField(max_length=6)

class SchoolDetails(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    school_ID=models.CharField(max_length=90,null=False,default=None)
    school_name=models.CharField(max_length=255,null=True,default=None)
    school_state=models.CharField(max_length=55,null=True,default=None)
    school_county=models.CharField(max_length=120,null=True,default=None)
    state_abv=models.CharField(max_length=6,null=False,default=None)
    zipcode=models.IntegerField(null=False,default=None)
    survey_taken=models.BooleanField(null=True,default=None)
    gradeLevel_WithPreschool=models.CharField(max_length=120,null=True,default=None)
    locale_number=models.IntegerField(null=True,default=None)
    locale=models.CharField(max_length=32,null=True,default=None)
    student_enrollment_range=models.CharField(max_length=108,null=True,default=None)
    student_free_reduced_lunch=models.CharField(max_length=108,null=True,default=None)
    student_nonwhite_population=models.CharField(max_length=108,null=True,default=None)
    implementation_level=models.CharField(max_length=120,null=True,default=None)
    unified_sports_component=models.BooleanField(null=True,default=None)
    youth_leadership_component=models.BooleanField(null=True,default=None)
    whole_school_component=models.BooleanField(null=True,default=None)
    survey_taken_year=models.IntegerField(null=False,default=None)               ##NEW COLUMNS
    sports_sports_teams = models.CharField(max_length=16,null=True,default=None)
    sports_unified_PE =	models.CharField(max_length=16,null=True,default=None)
    sports_unified_fitness=models.CharField(max_length=16,null=True,default=None)
    sports_unified_esports=models.CharField(max_length=16,null=True,default=None)
    sports_young_athletes=models.CharField(max_length=16,null=True,default=None)
    sports_unified_developmental_sports=models.CharField(max_length=16,null=True,default=None)
    leadership_unified_inclusive_club=models.CharField(max_length=16,null=True,default=None)
    leadership_youth_training=models.CharField(max_length=16,null=True,default=None)
    leadership_athletes_volunteer=models.CharField(max_length=16,null=True,default=None)
    leadership_youth_summit=models.CharField(max_length=16,null=True,default=None)
    leadership_activation_committe=models.CharField(max_length=16,null=True,default=None)
    engagement_spread_word_campaign=models.CharField(max_length=16,null=True,default=None)
    engagement_fansinstands=models.CharField(max_length=16,null=True,default=None)
    engagement_sports_day=models.CharField(max_length=16,null=True,default=None)
    engagement_fundraisingevent=models.CharField(max_length=16,null=True,default=None)
    engagement_SO_play=models.CharField(max_length=16,null=True,default=None)
    engagement_fitness_challenge=models.CharField(max_length=16,null=True,default=None)
    special_education_teachers=models.CharField(max_length=48,null=True,default=None)
    general_education_teachers=models.CharField(max_length=48,null=True,default=None)
    physical_education_teachers=models.CharField(max_length=48,null=True,default=None)
    adapted_pe_teachers=models.CharField(max_length=48,null=True,default=None)
    athletic_director=models.CharField(max_length=48,null=True,default=None)
    students_with_idd=models.CharField(max_length=48,null=True,default=None)
    students_without_idd=models.CharField(max_length=48,null=True,default=None)
    school_administrators=models.CharField(max_length=48,null=True,default=None)
    parents_of_students_with_idd=models.CharField(max_length=48,null=True,default=None)
    parents_of_students_without_idd=models.CharField(max_length=48,null=True,default=None)
    school_psychologist=models.CharField(max_length=48,null=True,default=None)
    special_olympics_state_program_staff=models.CharField(max_length=48,null=True,default=None)
    elementary_school_playbook=models.CharField(max_length=108,null=True,default=None)
    middle_level_playbook=models.CharField(max_length=108,null=True,default=None)
    high_school_playbook=models.CharField(max_length=108,null=True,default=None)
    special_olympics_state_playbook=models.CharField(max_length=48,null=True,default=None)
    special_olympics_fitness_guide_for_schools=models.CharField(max_length=108,null=True,default=None)
    unified_physical_education_resource=models.CharField(max_length=108,null=True,default=None)
    special_olympics_young_athletes_activity_guide=models.CharField(max_length=108,null=True,default=None)
    inclusive_youth_leadership_training_faciliatator_guide=models.CharField(max_length=108,null=True,default=None)
    planning_and_hosting_a_youth_leadership_experience=models.CharField(max_length=108,null=True,default=None)
    unified_classoom_lessons_and_activities=models.CharField(max_length=108,null=True,default=None)
    generation_unified_youtube_channel_or_videos=models.CharField(max_length=108,null=True,default=None)
    inclusion_tiles_game_or_facilitator_guide=models.CharField(max_length=108,null=True,default=None)
    students_with_intellectual_disability=models.CharField(max_length=32,null=True,default=None)
    students_without_intellectual_disability=models.CharField(max_length=32,null=True,default=None)
    the_school_as_a_whole=models.CharField(max_length=32,null=True,default=None)
    increase_in_understanding_language_of_disability=models.CharField(max_length=32,null=True,default=None)
    increasing_confidence_of_students_with_idd=models.CharField(max_length=32,null=True,default=None)
    opportunities_for_students_idd_to_work_together=models.CharField(max_length=32,null=True,default=None)
    creating_a_more_socially_inclusive_school_environment=models.CharField(max_length=32,null=True,default=None)
    raising_awareness_about_students_with_idd=models.CharField(max_length=32,null=True,default=None)
    increasing_participation_of_students_with_idd=models.CharField(max_length=32,null=True,default=None)
    reducing_bullying_teasing=models.CharField(max_length=32,null=True,default=None)
    increasing_confidence_of_students_without_idd=models.CharField(max_length=32,null=True,default=None)
    increasing_participation_of_students_without_idd=models.CharField(max_length=32,null=True,default=None)
    increasing_attendance_of_students_with_idd=models.CharField(max_length=32,null=True,default=None)
    reducing_disciplinary_referrals_for_students_with_idd=models.CharField(max_length=32,null=True,default=None)
    increasing_attendance_of_students_without_idd=models.CharField(max_length=32,null=True,default=None)
    reducing_disciplinary_referrals_for_students_without_idd=models.CharField(max_length=32,null=True,default=None)
    num_components = models.FloatField(null=True,default=None)

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)


