# Generated by Django 3.2.18 on 2023-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ID', models.CharField(default=None, max_length=90)),
                ('school_name', models.CharField(default=None, max_length=255, null=True)),
                ('school_state', models.CharField(default=None, max_length=55, null=True)),
                ('school_county', models.CharField(default=None, max_length=120, null=True)),
                ('state_abv', models.CharField(default=None, max_length=6)),
                ('zipcode', models.IntegerField(default=None)),
                ('survey_taken', models.BooleanField(default=None, null=True)),
                ('gradeLevel_WithPreschool', models.CharField(default=None, max_length=120, null=True)),
                ('locale_number', models.IntegerField(default=None, null=True)),
                ('locale', models.CharField(default=None, max_length=32, null=True)),
                ('student_enrollment_range', models.CharField(default=None, max_length=56, null=True)),
                ('student_free_reduced_lunch', models.CharField(default=None, max_length=56, null=True)),
                ('student_nonwhite_population', models.CharField(default=None, max_length=56, null=True)),
                ('implementation_level', models.CharField(default=None, max_length=120, null=True)),
                ('unified_sports_component', models.BooleanField(default=None)),
                ('youth_leadership_component', models.BooleanField(default=None)),
                ('whole_school_component', models.BooleanField(default=None, null=True)),
                ('survey_taken_year', models.IntegerField(default=None)),
            ],
        ),
    ]
