# Generated by Django 3.2.18 on 2023-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='datetime',
            field=models.DateTimeField(null=True, blank=True),  # Allow null and blank values
            preserve_default=False,
        ),
    ]
