# Generated by Django 5.0.4 on 2024-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_schooldetails_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooldetails",
            name="datetime",
        ),
        migrations.AddField(
            model_name="schooldetails",
            name="num_components",
            field=models.IntegerField(default=None),
        ),
    ]
