# Generated by Django 5.0.4 on 2024-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_remove_schooldetails_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooldetails",
            name="num_components",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
