# Generated by Django 5.0.4 on 2024-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_schooldetails_num_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooldetails",
            name="num_components",
            field=models.FloatField(default=None, null=True),
        ),
    ]
