# Generated by Django 3.2.18 on 2023-03-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20230327_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolInfo',
        ),
    ]
