# Generated by Django 3.2.18 on 2023-04-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_delete_schoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='sports_sports_teams',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
