# Generated by Django 3.2.18 on 2023-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_schooldetails_sports_sports_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='adapted_pe_teachers',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='athletic_director',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='creating_a_more_socially_inclusive_school_environment',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='elementary_school_playbook',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_SO_play',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_fansinstands',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_fitness_challenge',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_fundraisingevent',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_sports_day',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='engagement_spread_word_campaign',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='general_education_teachers',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='generation_unified_youtube_channel_or_videos',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='high_school_playbook',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='inclusion_tiles_game_or_facilitator_guide',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='inclusive_youth_leadership_training_faciliatator_guide',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increase_in_understanding_language_of_disability',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_attendance_of_students_with_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_attendance_of_students_without_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_confidence_of_students_with_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_confidence_of_students_without_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_participation_of_students_with_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='increasing_participation_of_students_without_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='leadership_activation_committe',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='leadership_athletes_volunteer',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='leadership_unified_inclusive_club',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='leadership_youth_summit',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='leadership_youth_training',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='middle_level_playbook',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='opportunities_for_students_idd_to_work_together',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='parents_of_students_with_idd',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='parents_of_students_without_idd',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='physical_education_teachers',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='planning_and_hosting_a_youth_leadership_experience',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='raising_awareness_about_students_with_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='reducing_bullying_teasing',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='reducing_disciplinary_referrals_for_students_with_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='reducing_disciplinary_referrals_for_students_without_idd',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='school_administrators',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='school_psychologist',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='special_education_teachers',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='special_olympics_fitness_guide_for_schools',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='special_olympics_state_playbook',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='special_olympics_state_program_staff',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='special_olympics_young_athletes_activity_guide',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='sports_unified_PE',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='sports_unified_developmental_sports',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='sports_unified_esports',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='sports_unified_fitness',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='sports_young_athletes',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='students_with_idd',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='students_with_intellectual_disability',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='students_without_idd',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='students_without_intellectual_disability',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='the_school_as_a_whole',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='unified_classoom_lessons_and_activities',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='schooldetails',
            name='unified_physical_education_resource',
            field=models.CharField(default=None, max_length=56, null=True),
        ),
    ]
