# Generated by Django 3.2.18 on 2023-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20230422_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetails',
            name='generation_unified_youtube_channel_or_videos',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='inclusion_tiles_game_or_facilitator_guide',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='inclusive_youth_leadership_training_faciliatator_guide',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='planning_and_hosting_a_youth_leadership_experience',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='special_olympics_fitness_guide_for_schools',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='special_olympics_young_athletes_activity_guide',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='student_enrollment_range',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='student_free_reduced_lunch',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='student_nonwhite_population',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='unified_classoom_lessons_and_activities',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='unified_physical_education_resource',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
    ]
