# Generated by Django 3.2.18 on 2023-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20230422_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetails',
            name='elementary_school_playbook',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='high_school_playbook',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='middle_level_playbook',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetails',
            name='special_olympics_state_playbook',
            field=models.CharField(default=None, max_length=108, null=True),
        ),
    ]
